[project]
name = "newbuddy"
version = "1.0.0"
description = "Jac client application: newbuddy"
entry-point = "main.jac"

[dependencies.npm]
jac-client-node = "1.0.4"
lodash = "latest"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"
"@types/react" = "latest"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client]
